[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR-ACTUAL-BACKEND-URL.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
